<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_PrivacyPolicy</name>
   <tag></tag>
   <elementGuidId>2f2e6d3f-f846-4300-9950-6ef5259e41ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[contains(@class,'consent__desc')]/preceding-sibling::label//span[contains(@class,'el-checkbox__inner')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
