stages:
  - test

jalanin_katalon_kre:
  stage: test
  image: katalonstudio/katalon:latest
  script:
    katalonc -noSplash -runMode=console -projectPath="C:\Users\MuhammadIbnuAthoilla\git\Sportstation\Sportstation.prj" -retry=0 -testSuitePath="Test Suites/Login and Logout" -browserType="Chrome" -executionProfile="default" -apiKey="40ac688e-370f-4077-8aba-b312ec70e152" -orgID=3493868 --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true -studioAssist.provider="katalon_ai"
  artifacts:
    when: always
    paths:
      - Reports/
    expire_in: 1 week