<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Checkout</name>
   <tag></tag>
   <elementGuidId>7ded5fde-8d66-437a-9fd6-ec80e786c7e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='primary'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.checkout-btn > button.el-button.el-button--primary.el-button--large.gt-button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'primary' and (text() = '
                  Checkout
                ' or . = '
                  Checkout
                ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0437d95f-017c-494e-ae60-75fdcebbcb87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>5e2be038-0aff-49e2-a48d-14cd859d2038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-button el-button--primary el-button--large gt-button</value>
      <webElementGuid>23ba12c7-4196-41a8-a1c0-31debf093317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>large</value>
      <webElementGuid>921c5ed4-6570-48ae-ae94-6cf3da5b9a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Checkout
                </value>
      <webElementGuid>80d53f21-0d74-4a6c-86be-6205f97b937d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-view&quot;)/div[1]/div[@class=&quot;gt-layout page-layout_pc&quot;]/section[@class=&quot;page-shop-cart page-view__child&quot;]/section[@class=&quot;gt-page-shop-cart&quot;]/section[@class=&quot;gt-page_shopcart&quot;]/section[@class=&quot;page-shopCart_container&quot;]/div[@class=&quot;page-shopCart_container_right&quot;]/div[@class=&quot;gt-skeleton&quot;]/div[@class=&quot;page-shopCart_container_right_content&quot;]/div[@class=&quot;checkout-btn&quot;]/button[@class=&quot;el-button el-button--primary el-button--large gt-button&quot;]</value>
      <webElementGuid>aa407e92-ad3b-4f9f-b6da-02e5f546d3fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='primary'])[2]</value>
      <webElementGuid>5bca5792-3d7c-4b9b-8d88-c6c187783a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-view']/div/div/section/section/section/section/div[2]/div/div/div/button</value>
      <webElementGuid>63898f6c-fe40-44be-9eb9-3ec554d08b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 20.000'])[4]/following::button[1]</value>
      <webElementGuid>bee17622-95fa-4382-a161-e68edcbba0a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::button[1]</value>
      <webElementGuid>aad6b01e-6f39-4797-a147-2057afbfb93f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/preceding::button[1]</value>
      <webElementGuid>f66270fe-6315-416e-9e6a-ef846541142d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>af6b3301-6515-47dc-81da-02dde61432f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'primary' and (text() = '
                  Checkout
                ' or . = '
                  Checkout
                ')]</value>
      <webElementGuid>5d35528f-3efa-4661-be5e-943f4f75bb23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
