<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ID_Product</name>
   <tag></tag>
   <elementGuidId>6336cf30-afee-41b5-95c6-ffe7347aa6fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.sku-code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-view']/div/div/div[2]/section/section/div/div[2]/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>97e79a95-d94d-47a8-a999-96f264d81846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sku-code</value>
      <webElementGuid>b0c08380-c1e6-4dab-936c-6b0a7f71ba3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          0888-AIWUK251209GGRE036
        </value>
      <webElementGuid>fe6a4ccc-2ccb-4c04-beb6-a9ef3ab48e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-view&quot;)/div[1]/div[@class=&quot;gt-layout page-layout_pc&quot;]/div[@class=&quot;page-view__child&quot;]/section[@class=&quot;page-pdp page-pdp&quot;]/section[@class=&quot;page-pdp_content&quot;]/div[@class=&quot;page-pdp_content__main&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;title&quot;]/span[@class=&quot;sku-code&quot;]</value>
      <webElementGuid>d7f55df4-75ab-44dd-b1ee-6def97fbdb2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-view']/div/div/div[2]/section/section/div/div[2]/div/span[2]</value>
      <webElementGuid>8560465a-b11c-4304-a090-bee137b72da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Airwalk'])[2]/following::span[1]</value>
      <webElementGuid>a5238e33-9126-48d3-b347-6e5b35eba78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 20.000'])[1]/preceding::span[1]</value>
      <webElementGuid>5bb3590e-b734-42f8-a4cd-fefb2bde5663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0888-AIWUK251209GGRE036']/parent::*</value>
      <webElementGuid>2b5febf2-c21f-4a10-a662-f67bb02044b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[2]/div/span[2]</value>
      <webElementGuid>65ff1438-a9cc-4316-b641-411c9f7fd409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
          0888-AIWUK251209GGRE036
        ' or . = '
          0888-AIWUK251209GGRE036
        ')]</value>
      <webElementGuid>27e6de98-e712-4d74-b978-c3b3006c6d7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
