<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_product</name>
   <tag></tag>
   <elementGuidId>07c665fd-debe-4ff1-8fce-e719cef9be87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.gt-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-view']/div/div/div[2]/section/div[2]/div[2]/div/section/div/div/div/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b8684341-8823-4184-8ad9-458ae2291b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gt-image</value>
      <webElementGuid>52621dde-93be-4a61-8cb2-16736f03f754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-view&quot;)/div[1]/div[@class=&quot;gt-layout page-layout_pc&quot;]/div[@class=&quot;page-view__child&quot;]/section[@class=&quot;page-pdp page-pdp&quot;]/div[@class=&quot;shop-more&quot;]/div[@class=&quot;shop-more__swiper&quot;]/div[@class=&quot;sp-swiper-container swiper-container-initialized swiper-container-horizontal&quot;]/section[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide swiper-slide-active&quot;]/div[@class=&quot;shop-more__swiper-item&quot;]/div[@class=&quot;shop-more__card&quot;]/div[@class=&quot;sp-plp-card&quot;]/div[@class=&quot;sp-plp-card__wrapper&quot;]/div[1]/div[@class=&quot;sp-plp-card__img&quot;]/img[@class=&quot;gt-image&quot;]</value>
      <webElementGuid>7de7b4ff-950a-4195-8652-82a6ae53f876</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-view']/div/div/div[2]/section/div[2]/div[2]/div/section/div/div/div/div/div/div/div/img</value>
      <webElementGuid>623a72eb-cf14-4fdf-993d-d24aceabdb75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/div/div/img</value>
      <webElementGuid>f39284a2-f9ff-49f4-be06-2d837b44ce19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
