<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Airwalk</name>
   <tag></tag>
   <elementGuidId>c2654ce1-e213-4633-a905-c24e8c97a778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.brand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-view']/div/div/div[2]/section/section/div/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1bf05e5d-1d2f-4d0b-8e2f-35d8fda90817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>brand</value>
      <webElementGuid>989aadc8-85a7-4678-a5fe-fe0d988285e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Airwalk
        </value>
      <webElementGuid>a03f7f74-49bf-4d13-830b-44fe4f20b94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-view&quot;)/div[1]/div[@class=&quot;gt-layout page-layout_pc&quot;]/div[@class=&quot;page-view__child&quot;]/section[@class=&quot;page-pdp page-pdp&quot;]/section[@class=&quot;page-pdp_content&quot;]/div[@class=&quot;page-pdp_content__main&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;title&quot;]/span[@class=&quot;brand&quot;]</value>
      <webElementGuid>eddbf1a1-7700-4819-9562-6c9a30251078</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-view']/div/div/div[2]/section/section/div/div[2]/div/span</value>
      <webElementGuid>3d5dc9f5-bc9f-4932-b81e-04471f0feb05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sports'])[1]/following::span[3]</value>
      <webElementGuid>00a6ffe8-d81b-4976-990d-7bd091935d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 20.000'])[1]/preceding::span[2]</value>
      <webElementGuid>339aba63-fb78-435c-be81-898c060d5500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/section/div/div[2]/div/span</value>
      <webElementGuid>ea377764-9f20-4623-be53-5ed7b2e9678e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
          Airwalk
        ' or . = '
          Airwalk
        ')]</value>
      <webElementGuid>9ea981a1-2d96-4a20-ac72-a142176ff3aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
