<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PrivacyPolicy</name>
   <tag></tag>
   <elementGuidId>44210d67-7893-4406-8edd-2fdb1d9f84b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.iframe-block-wrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-view']/div/div/div[2]/section/div/div/section/div/div/section/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.iframe-block-wrap</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>40984dfb-c3b1-434e-b31d-2069e3e4c342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframe-block-wrap</value>
      <webElementGuid>67c27e02-34f7-4e5d-a1bd-6166c16e6324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-view&quot;)/div[1]/div[@class=&quot;gt-layout page-layout_pc&quot;]/div[@class=&quot;gt-plp-page page-view__child&quot;]/section[@class=&quot;sp-landing-page&quot;]/div[@class=&quot;sp-landingpage-collection&quot;]/div[@class=&quot;sp-row&quot;]/section[@class=&quot;row-box&quot;]/div[@class=&quot;sp-row-wrapper&quot;]/div[1]/section[@class=&quot;sp-landing-textblock text-block&quot;]/div[@class=&quot;iframe-block-wrap&quot;]</value>
      <webElementGuid>66a38b2e-2d2c-4f40-9946-f9472306c014</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-view']/div/div/div[2]/section/div/div/section/div/div/section/div</value>
      <webElementGuid>a9f5353a-1992-4cf2-860d-f36a1a85eb19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free Shipping!'])[2]/following::div[7]</value>
      <webElementGuid>970bc156-b364-4a70-b919-a016c1fc7871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/preceding::div[5]</value>
      <webElementGuid>ed99ebb9-ce56-4236-bfc2-3d31b0938e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/preceding::div[6]</value>
      <webElementGuid>1e93813f-eac8-4365-a74b-e874e7d609ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/section/div/div/section/div</value>
      <webElementGuid>5d9f3468-e66d-4320-b69d-9f52e9b4ba4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
