<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_acceptAllCookies</name>
   <tag></tag>
   <elementGuidId>08b9e9bd-aba9-4c71-9579-fe43e065697d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nuxt-app']/div[6]/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.cookie-consent__button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Accept All Cookies&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>46796779-bc51-44fa-a589-8ff2e76c768b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cookie-consent__button</value>
      <webElementGuid>b9a61ce6-0439-4ecf-b7fb-55174c428317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Accept All Cookies
      </value>
      <webElementGuid>80a9d1fe-a693-4017-9537-2d8126271914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nuxt-app&quot;)/div[@class=&quot;cookie-consent&quot;]/div[@class=&quot;cookie-consent__wrapper&quot;]/button[@class=&quot;cookie-consent__button&quot;]</value>
      <webElementGuid>1217c02c-230a-4928-9206-b0d789237f38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nuxt-app']/div[6]/div[2]/button</value>
      <webElementGuid>e9bbd764-db49-4cf0-94f4-b6a23d31b268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/following::button[1]</value>
      <webElementGuid>5d143d27-05c2-48f2-aae7-2d1834e14e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accept All Cookies']/parent::*</value>
      <webElementGuid>b4aca052-8da5-4456-894d-eb6b66a00468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/button</value>
      <webElementGuid>979e8ee1-96d9-49f5-adac-2fc8d30903e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
        Accept All Cookies
      ' or . = '
        Accept All Cookies
      ')]</value>
      <webElementGuid>1232153f-7aeb-4b94-832b-408ba079c11d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
