<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_sms</name>
   <tag></tag>
   <elementGuidId>01c0b722-827b-4dd4-a5ca-cf170563acb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = ' 
              SMS
            ' or . = ' 
              SMS
            ')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-view']/div/div/div[2]/div/div/div[2]/div[2]/section[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>section >> internal:has-text=&quot;SMS&quot;i >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>19418ddd-52ae-48fa-9c13-f0bacdef57dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-dialog__body-action-item</value>
      <webElementGuid>1b03a569-5146-4248-a26d-af059521fe79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
              SMS
            </value>
      <webElementGuid>ac7fbf79-88d1-4c1b-a9d0-897646c71149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-view&quot;)/div[1]/div[@class=&quot;gt-layout page-layout_pc&quot;]/div[@class=&quot;digibox-register-container page-view__child&quot;]/div[@class=&quot;el-dialog__wrapper verification_dialog sp-dialog&quot;]/div[@class=&quot;el-dialog&quot;]/div[@class=&quot;el-dialog__body&quot;]/div[@class=&quot;el-dialog__body-action&quot;]/section[@class=&quot;el-container&quot;]/div[@class=&quot;el-dialog__body-action-item&quot;]</value>
      <webElementGuid>04535172-2313-45b5-82f5-1a639dde5d61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-view']/div/div/div[2]/div/div/div[2]/div[2]/section[2]/div</value>
      <webElementGuid>acc1ff51-74df-4db0-8830-ab38ed7ad029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verification Method'])[1]/following::div[4]</value>
      <webElementGuid>b740b90b-d870-4069-8a9a-8ce2b22631a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Term &amp; Conditions'])[1]/following::div[8]</value>
      <webElementGuid>3cbe78e5-225b-4982-9ade-fbbd275981f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[5]</value>
      <webElementGuid>55780d90-75ee-454c-bcae-5c40ae349f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In with MAPCLUB'])[1]/preceding::div[5]</value>
      <webElementGuid>ebbe5905-b5cd-4d31-9092-84c1c3e408de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div</value>
      <webElementGuid>443f3b20-1385-4c43-911e-388d712e1444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' 
              SMS
            ' or . = ' 
              SMS
            ')]</value>
      <webElementGuid>d712bcd4-fc77-4b2f-a880-ec38afce298f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
