<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtField_dayOfBirth</name>
   <tag></tag>
   <elementGuidId>33b86ce7-9dfb-4420-97eb-56ca7edb1659</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.el-date-editor.width_fill.el-input.el-input--medium.el-input--prefix.el-input--suffix.el-date-editor--date.gt-date-picker.gt-radius-undefined.gt-border-undefined.gt-borderColor-undefined > input.el-input__inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Date of Birth&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11a38b38-ffbc-4042-b148-97c37e895d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db12f247-bf84-4d45-8904-be23b8f443f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d3be4950-17b2-44a4-aadc-c86cd1751bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Date of Birth</value>
      <webElementGuid>453dd46c-9e2f-42cb-b4c9-13e2c736fcd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>aae1e59d-c919-4e26-b53e-f601492a4802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-view&quot;)/div[1]/div[@class=&quot;gt-layout page-layout_pc&quot;]/div[@class=&quot;signup-container page-view__child&quot;]/section[@class=&quot;register-page-index&quot;]/div[@class=&quot;register-page-index__right&quot;]/div[@class=&quot;signup-section&quot;]/form[@class=&quot;el-form gt-simple-form el-form--label-top&quot;]/div[@class=&quot;el-form-item gt-form-item is-required el-form-item--medium date-of-birth&quot;]/div[@class=&quot;el-form-item__content&quot;]/div[@class=&quot;el-date-editor width_fill el-input el-input--medium el-input--prefix el-input--suffix el-date-editor--date gt-date-picker gt-radius-undefined gt-border-undefined gt-borderColor-undefined&quot;]/input[@class=&quot;el-input__inner&quot;]</value>
      <webElementGuid>7953cb16-98b1-4457-9433-2dac1e816e69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='']</value>
      <webElementGuid>6f331ee9-5350-4fa8-9b83-a2a51b33eaaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-view']/div/div/div[2]/section/div[2]/div[2]/form/div[8]/div/div/input</value>
      <webElementGuid>572c17a4-9cb1-4bb7-9a00-850d335c86c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>0146d5bb-f819-4573-879e-aab00055c097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Date of Birth']</value>
      <webElementGuid>222c59c9-ce50-4bf5-8394-5dfbd55c9778</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
