<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_reload</name>
   <tag></tag>
   <elementGuidId>5c1e8fca-fd44-460e-a693-74d89a766298</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='refresh']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#refresh</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>350c8cb0-3444-4daa-96a4-26d1afd5aaa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refresh</value>
      <webElementGuid>c4d24d1a-17ac-4246-ab31-cc9655797570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md but textu f36</value>
      <webElementGuid>5008f840-2fea-46c8-9915-b4d8e76ff793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(chkl())r();</value>
      <webElementGuid>c0ad13be-0ff0-4cdb-b532-863be6f343bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>6a2252cb-4638-4fda-b867-97ab7ae2735e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refresh&quot;)</value>
      <webElementGuid>77eb3b54-5714-4df8-ba80-c242687defca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='refresh']</value>
      <webElementGuid>1a6877b7-f124-4226-86ad-86f0ae8b1ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='webmail']/div/div/div/main/div[2]/div/div/div/div[6]/button</value>
      <webElementGuid>a0fb537e-1882-4be6-bfd0-54f253a6ea38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/following::button[1]</value>
      <webElementGuid>0d13173a-2c57-441d-ae5e-e55ce9bd08fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::button[2]</value>
      <webElementGuid>63004e44-7a5b-479f-81af-32bd408cba9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::button[1]</value>
      <webElementGuid>146ad12c-7ca7-4870-89ef-5a50d93566ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button</value>
      <webElementGuid>a528b607-91fc-4399-b25a-a3aef3296a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'refresh' and (text() = '' or . = '')]</value>
      <webElementGuid>8a444033-b84d-42a1-a39e-372c9c5a2efc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
