<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Checkout</name>
   <tag></tag>
   <elementGuidId>aca7cf0e-ae69-4eab-9389-396fd0e68cc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.el-button.action-btn--onpage.el-button--primary.el-button--large.gt-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='primary'])[7]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'primary' and (text() = '
        Checkout
      ' or . = '
        Checkout
      ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5235a91e-23b0-43d4-a2ce-8e2f650035cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>9629a88f-bae9-4cc8-a875-6e4200a01e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-button action-btn--onpage el-button--primary el-button--large gt-button</value>
      <webElementGuid>eb8248e7-309c-4f74-ae71-af20778910f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>large</value>
      <webElementGuid>c35e2814-2862-44ef-a46c-4c1ea0ab8e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Checkout
      </value>
      <webElementGuid>4b9d64e6-dd95-44f6-919e-cc8abff84f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-view&quot;)/div[1]/div[@class=&quot;gt-layout page-layout_pc&quot;]/div[@class=&quot;page-view__child&quot;]/section[@class=&quot;page-checkout ss-page-checkout&quot;]/div[@class=&quot;right&quot;]/section[@class=&quot;right-container&quot;]/section[@class=&quot;action&quot;]/section[@class=&quot;gt-page_checkout__accept&quot;]/button[@class=&quot;el-button action-btn--onpage el-button--primary el-button--large gt-button&quot;]</value>
      <webElementGuid>c758d842-7d9c-49e2-a151-16ab8b03d801</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='primary'])[7]</value>
      <webElementGuid>bac97e4a-6bd4-4e68-b7b4-f1eadf047276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-view']/div/div/div[2]/section/div[2]/section/section[2]/section/button</value>
      <webElementGuid>529e4bd7-eb40-4943-b24d-bf346039f3b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='data protection policy'])[1]/following::button[1]</value>
      <webElementGuid>c104a3ac-dc2c-46a9-af2e-082fbef458d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[3]/preceding::button[1]</value>
      <webElementGuid>45c629bf-0be8-4e40-bf42-de31b255384c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/section/button</value>
      <webElementGuid>a6927645-c9ef-4cac-90ab-bbd32f284e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'primary' and (text() = '
        Checkout
      ' or . = '
        Checkout
      ')]</value>
      <webElementGuid>fd66a947-9e9b-4c45-9aa0-3eac75a7e269</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
