<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_midTrans</name>
   <tag></tag>
   <elementGuidId>f0a1b3bc-9db3-489a-9544-43cf440d3081</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//label[@id='pay']/span/span)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d9eba52b-ffd4-4638-8674-96669807f831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-radio__inner</value>
      <webElementGuid>2d1daaab-11e5-403b-941f-3af360d1cc1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-view&quot;)/div[1]/div[@class=&quot;gt-layout page-layout_pc&quot;]/div[@class=&quot;page-view__child&quot;]/section[@class=&quot;page-checkout ss-page-checkout&quot;]/div[@class=&quot;left&quot;]/section[@class=&quot;page-checkout_payment&quot;]/section[1]/div[@class=&quot;sp-payment-methods&quot;]/div[@class=&quot;sp-payment-methods__item&quot;]/div[@class=&quot;sp-payment-methods__item-top&quot;]/label[@id=&quot;pay&quot;]/span[@class=&quot;el-radio__input&quot;]/span[@class=&quot;el-radio__inner&quot;]</value>
      <webElementGuid>f0b04e37-48fe-46be-a661-c1d2bc717cf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//label[@id='pay']/span/span)[2]</value>
      <webElementGuid>55321d73-24ff-43bb-ab52-8534c9a452d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/section/div/div[2]/div/label/span/span</value>
      <webElementGuid>593973ea-1bb1-4a52-a2ff-35605af1e6e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
