<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Left</name>
   <tag></tag>
   <elementGuidId>a150f35d-dd12-4d1d-beb5-56a9d51e5621</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-view']/div/div/div[2]/section/div[4]/div[2]/section/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>section.gt-pdp_recommend > div.sp-swiper-container.swiper-container-initialized.swiper-container-horizontal > div.swiper-button-next</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3bebc7a4-243c-450b-ac10-d356e874f835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swiper-button-next</value>
      <webElementGuid>bb8d0677-62ee-4e1f-a7c8-74edcb4baaae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>adbb31ea-51dd-4669-841f-85d74b4ddc4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fb2b9c71-3767-4bfa-ad24-2f55539ae722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Next slide</value>
      <webElementGuid>d2e998c4-1c61-478a-84cf-6184bf04406f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>61d69543-67b0-4548-b57c-887e6f5e7bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-view&quot;)/div[1]/div[@class=&quot;gt-layout page-layout_pc&quot;]/div[@class=&quot;page-view__child&quot;]/section[@class=&quot;page-pdp page-pdp&quot;]/div[4]/div[@class=&quot;unbxd&quot;]/section[@class=&quot;gt-pdp_recommend&quot;]/div[@class=&quot;sp-swiper-container swiper-container-initialized swiper-container-horizontal&quot;]/div[@class=&quot;swiper-button-next&quot;]</value>
      <webElementGuid>6c472ac0-6cf2-4681-8048-9191d58a9d40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-view']/div/div/div[2]/section/div[4]/div[2]/section/div/div</value>
      <webElementGuid>c558a878-7c8b-413e-aa01-6894632ff6a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/section/div/div</value>
      <webElementGuid>a3dc21dd-6183-42a3-ba6b-e7ad9a0047cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
