<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Right</name>
   <tag></tag>
   <elementGuidId>3864fc3f-a2a6-48fb-b751-19577b13e1e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-view']/div/div/div[2]/section/div[4]/div[2]/section/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>section.gt-pdp_recommend > div.sp-swiper-container.swiper-container-initialized.swiper-container-horizontal > div.swiper-button-prev</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8eee7845-74fe-463e-85f5-cc3c96e30e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swiper-button-prev</value>
      <webElementGuid>4fc736e7-b051-4034-b39f-b196014ea35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5027c077-8ad8-486e-84b8-702b2eb4c318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5e4710d7-f9af-47eb-8417-05209e840ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Previous slide</value>
      <webElementGuid>ac21d1f0-8fa1-403f-9b4c-85ae5c7479cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a01e6ae3-343c-47a5-90da-175814689b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-view&quot;)/div[1]/div[@class=&quot;gt-layout page-layout_pc&quot;]/div[@class=&quot;page-view__child&quot;]/section[@class=&quot;page-pdp page-pdp&quot;]/div[4]/div[@class=&quot;unbxd&quot;]/section[@class=&quot;gt-pdp_recommend&quot;]/div[@class=&quot;sp-swiper-container swiper-container-initialized swiper-container-horizontal&quot;]/div[@class=&quot;swiper-button-prev&quot;]</value>
      <webElementGuid>6c916e19-15eb-4eb9-aeaf-ab962eb63ec8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-view']/div/div/div[2]/section/div[4]/div[2]/section/div/div[2]</value>
      <webElementGuid>8233e33e-ed0f-413f-9518-8b760df31839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/section/div/div[2]</value>
      <webElementGuid>95c9243d-e76a-4e8c-9db8-1f3e35c62fff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
