<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Filter</name>
   <tag></tag>
   <elementGuidId>790929c7-680a-450b-94dd-20f87bc8af00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[normalize-space()='Filters']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
