<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Edit</name>
   <tag></tag>
   <elementGuidId>97e426a1-8dd6-4b2e-a495-1d38098802a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-collapse-head-2092']/section/div/div[3]/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.address-operation > button.el-button.el-button--text.gt-button > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e376f2bc-3d10-4da1-ba92-b1353da6db4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>6e1ee55e-3733-4fcf-9fec-a41b6d32ea35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-collapse-head-2092&quot;)/section[@class=&quot;item-title&quot;]/div[@class=&quot;gt-address_list-item__content&quot;]/div[@class=&quot;address-operation&quot;]/button[@class=&quot;el-button el-button--text gt-button&quot;]/span[1]</value>
      <webElementGuid>977b2f0b-e958-4984-aefc-ace12104fcd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-collapse-head-2092']/section/div/div[3]/button/span</value>
      <webElementGuid>974003bd-11b3-4f9a-832b-254684031f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::span[5]</value>
      <webElementGuid>21c52199-23f8-4bf9-855f-21aa5a573017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping Address'])[1]/following::span[6]</value>
      <webElementGuid>3de7438c-8781-4569-a6c1-06f4539f6fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::span[1]</value>
      <webElementGuid>6a3fb150-9872-4741-b898-ab3abffab667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal'])[1]/preceding::span[4]</value>
      <webElementGuid>086f59fe-ef53-45f2-93a4-1cf505539410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>d0f0b700-4791-4de4-9759-93398f2e21c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span</value>
      <webElementGuid>4ef88fbd-5922-476e-9fe0-93320a5c6d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>be857e5f-dc89-42f5-9490-223b04af53d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
