<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_hi,username</name>
   <tag></tag>
   <elementGuidId>fe7ae522-a903-4a32-9ebc-d7fc26dd277e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>/html/body/div[1]/div/div/div[1]/div/div/div[1]/div[1]/div/div[3]/div/div/span/div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-view']/div/div/div/div/div/div[3]/div/div/span/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;I ibn toi&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cf413c37-eaa8-433d-be8c-bb2c783bd5ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gt-header-my__fw</value>
      <webElementGuid>34f16e86-5cb1-453a-b97a-fd5a3a660bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I</value>
      <webElementGuid>e45ac81f-8315-4da2-aa57-cf7136332a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-view&quot;)/div[1]/div[@class=&quot;gt-layout page-layout_pc&quot;]/div[@class=&quot;gt-header common-header&quot;]/div[@class=&quot;header-top&quot;]/div[@class=&quot;cell-panel&quot;]/div[@class=&quot;cell cell-login&quot;]/div[@class=&quot;gt-header-my&quot;]/div[@class=&quot;gt-header-my__drop el-dropdown&quot;]/span[@class=&quot;el-dropdown-link el-dropdown-selfdefine&quot;]/div[@class=&quot;gt-header-my__wrapper&quot;]/div[@class=&quot;gt-header-my__fw&quot;]</value>
      <webElementGuid>0e19e903-b620-4b32-8b9a-b8922ef5796a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-view']/div/div/div/div/div/div[3]/div/div/span/div/div</value>
      <webElementGuid>97f1dc16-0ad3-4115-a3a6-d78076120e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Store Location'])[1]/following::div[5]</value>
      <webElementGuid>e7617c8e-40a5-41e1-a22b-aad7b89bbec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Track Order'])[1]/following::div[6]</value>
      <webElementGuid>d38024a2-d7a3-4b8c-add3-3df16032481e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ibn toi'])[1]/preceding::div[1]</value>
      <webElementGuid>3d130bca-5f12-4c7e-b85e-d235a8f56c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi,ibn toi'])[1]/preceding::div[2]</value>
      <webElementGuid>c7b488f6-1577-48cc-a2a1-0632c07b5f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='I']/parent::*</value>
      <webElementGuid>81d8342c-e1ac-41c6-9732-ddd84d534c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div</value>
      <webElementGuid>261aef35-5219-453b-9201-c5426195a977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'I' or . = 'I')]</value>
      <webElementGuid>dfa1690c-2634-421b-b85b-07dcb6ebb6f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
